apps/front/forms.py
from wtforms import StringField, IntegerField
from ..forms import BaseForm
from wtforms.validators import Regexp, EqualTo, ValidationError, InputRequired
from utils import cache


class SignupForm(BaseForm):
    telephone = StringField(validators=[Regexp(r"^[1](([3][0-9])|([4][5-9])|([5][0-3,5-9])|([6][5,6])|([7][0-8])|([8][0-9])|([9][1,8,9]))[0-9]{8}$", message="请输入正确格式的手机号码")])
    sms_captcha = StringField(validators=[Regexp(r"\w{6}", message="请输入正确格式的短信验证码")])
    username = StringField(validators=[Regexp(r".{2,20}", message="请输入正确格式的用户名")])
    password = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}", message="请输入正确格式的密码")])
    password2 = StringField(validators=[EqualTo("password", message="两次输入的密码不一致")])
    graph_captcha = StringField(validators=[Regexp(r"\w{4}", message="请输入正确格式的验证码")])

    def validate_sms_captcha(self, field):
        sms_captcha = field.data
        print(sms_captcha)
        telephone = self.telephone.data
        print(telephone)
        sms_captcha_cache = cache.get(telephone)
        if not sms_captcha_cache or sms_captcha.lower() != sms_captcha_cache.lower():
            raise ValidationError(message="短信验证码错误")

    def validate_graph_captcha(self, field):
        graph_captcha = field.data
        graph_captcha_cache = cache.get(graph_captcha.lower())
        if not graph_captcha_cache :
            raise ValidationError(message="图形验证码错误")


class SigninForm(BaseForm):
    telephone = StringField(validators=[Regexp(r"^[1](([3][0-9])|([4][5-9])|([5][0-3,5-9])|([6][5,6])|([7][0-8])|([8][0-9])|([9][1,8,9]))[0-9]{8}$",
               message="请输入正确格式的手机号码")])
    password = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}", message="请输入正确格式的密码")])
    remember = StringField()


class AddPostForm(BaseForm):
    title = StringField(validators=[InputRequired(message="请输入标题")])
    content = StringField(validators=[InputRequired(message="请输入内容")])
    board_id = IntegerField(validators=[InputRequired(message="请输入板块id")])

apps/common/views.py
from flask.blueprints import Blueprint
from flask import views, render_template, make_response, request
from io import BytesIO
from utils import cache, restful
from utils.captcha import Captcha
from utils.tencent_sms import send_sms, generate_captcha
from apps.common.forms import SMSCaptchaForm

bp = Blueprint("common", __name__, url_prefix="/common")


@bp.route('/')
def index():
    return "common"


@bp.route('/captcha/')
def graph_captcha():
    text, image = Captcha.gene_graph_captcha()
    cache.set(text.lower(), text.lower())
    out = BytesIO()
    with image as image:
        image.save(out, 'png')
        out.seek(0)
        resp = make_response(out.read())
        resp.content_type = 'image/png'
        return resp


@bp.route('/sms_captcha/', methods=["POST"])
def sms_captcha():
    form = SMSCaptchaForm(request.form)
    if form.validate():
        telephone = form.telephone.data
        captcha = generate_captcha()
        if send_sms(telephone=telephone, captcha=captcha):
            cache.set(telephone, captcha)
            return restful.success()
        return restful.params_error("验证码获取失败")
    else:
        return restful.params_error(msg="参数错误")

apps/front/__init__.py
from .views import bp
from . import hooks

apps/front/views.py
from flask.blueprints import Blueprint
from flask import views, render_template, request, redirect, url_for
from flask import session, g
from flask_paginate import Pagination, get_page_parameter

from .forms import SignupForm, SigninForm, AddPostForm
from config import FRONT_USER_ID, PER_PAGE
from utils import restful
from .model import FrontUser
from .model import db
from utils import safeutils
from ..models import BannerModel
from ..models import BoardModel
from ..models import PostModel
from .decorators import login_required

bp = Blueprint("front", __name__)


@bp.route('/')
def index():
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(3)
    boards = BoardModel.query.all()
    # 获取当前页
    page = request.args.get(get_page_parameter(), type=int, default=1)
    start = (page-1)*PER_PAGE
    end = start + PER_PAGE
    posts = PostModel.query.slice(start, end)
    pagination = Pagination(bs_version=3, page=page, total=PostModel.query.count())
    context = {
        'banners': banners,
        'boards': boards,
        'posts': posts,
        'pagination': pagination
    }
    return render_template('front/front_index.html', **context)


@bp.route('/apost/', methods=["GET", "POST"])
@login_required
def apost():
    if request.method == "GET":
        boards = BoardModel.query.all()
        context = {
            "boards": boards
        }
        return render_template('front/front_apost.html', **context)
    form = AddPostForm(request.form)
    if form.validate():
        title = form.title.data
        content = form.content.data
        board_id = form.board_id.data
        board = BoardModel.query.get(board_id)
        if not board:
            return restful.params_error("板块不存在")
        post = PostModel(title=title, content=content, board_id=board_id)
        post.author = g.front_user
        db.session.add(post)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(msg=form.get_error())


class SignupView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/front_signup.html', return_to=return_to)
        return render_template('front/front_signup.html')

    def post(self):
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password.data
            user = FrontUser(telephone=telephone, user_name=username, password=password)
            db.session.add(user)
            db.session.commit()

            return restful.success()
        return restful.params_error(form.get_error())


class SigninView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and return_to != url_for('front.signup') and safeutils.is_safe_url(return_to):
            return render_template('front/front_signin.html', return_to=return_to)

        return render_template('front/front_signin.html')

    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remember.data
            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[FRONT_USER_ID] = user.id
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return restful.params_error(msg="手机号或密码错误")
        else:
            return restful.params_error(msg=form.get_error())


bp.add_url_rule('/signup/', view_func=SignupView.as_view('signup'))
bp.add_url_rule('/signin/', view_func=SigninView.as_view('signin'))

templates/front/front_apost.html
{% extends 'front/front_base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}
    发布帖子
{% endblock %}

{% block head %}
    <script src="{{ static('ueditor/ueditor.config.js') }}"></script>
    <script src="{{ static('ueditor/ueditor.all.min.js') }}"></script>
    <script src="{{ static('front/js/front_apost.js') }}"></script>
{% endblock %}

{% block body %}
    <form action="" method="post">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">标题</span>
                <input type="text" class="form-control" name="title">
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">板块</span>
                <select name="board_id" class="form-control">
                    {% set index = 0 %}
                    {% for board in boards %}
                        <option value={{ board.id }}>{{ board.name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group">
            <script id="editor" type="text/plain" style="height: 500px"></script>
        </div>
        <div class="form-group">
            <button id="submit-btn" class="btn btn-danger">发布帖子</button>
        </div>
    </form>
{% endblock %}

templates/front/front_base.html
{% from 'common/_macros.html' import static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    {% include 'common/_heads.html' %}
    <link rel="stylesheet" href="{{ static('front/css/front_base.css') }}">
    <title>{% block title %}
    {% endblock %}</title>
    {% block head %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">BBS论坛</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/">首页</a></li>

            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="请输入关键字">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if g.front_user %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" type="button" id="dropdownMenu1"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            {{ g.front_user.user_name }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="#">个人中心</a></li>
                            <li><a href="#">设置</a></li>
                            <li><a href="#">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{{ url_for('front.signin') }}">登录</a></li>
                    <li><a href="{{ url_for('front.signup') }}">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="main-container">
    {% block body %}{% endblock %}
</div>
</body>
</html>

templates/front/front_index.html
{% extends 'front/front_base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}
    BBS论坛
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ static('front/css/front_index.css') }}">
{% endblock %}

{% block body %}
    <div class="lg-container">
        <div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>

            <!-- 轮播图s -->
            <div class="carousel-inner" role="listbox">
                {% for banner in banners %}
                    {% if loop.first %}
                        <div class="item active">
                    {% else %}
                        <div class="item">
                    {% endif %}
                <a href="{{ banner.link_url }}"><img src="{{ banner.image_url }}" alt="..."></a>
                </div>
                {% endfor %}
                </div>

                <!-- 左右切换的控制按钮 -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <div class="post-group">
                <ul class="post-group-head">
                    <li class="active"><a href="#">最新</a></li>
                    <li><a href="#">精华帖</a></li>
                    <li><a href="#">点赞最多</a></li>
                    <li><a href="#">评论最多</a></li>
                </ul>
                <ul class="post-list-group">
                    {% for post in posts %}
                        <li>
                            <div class="author-avator-group">
                                <img src="{{ post.author.avator or url_for('static',filename='common/images/logo.png') }}"
                                     alt="">
                            </div>
                            <div class="post-info-group">
                                <p class="post-title">{{ post.title }}</p>
                                <p class="post-info">
                                    <span>作者：{{ post.author.user_name }}</span>
                                    <span>发表时间：{{ post.create_time }}</span>
                                    <span>评论：0</span>
                                    <span>阅读数：0</span>
                                </p>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                <div style="text-align: center">
                    {{ pagination.links }}
                </div>
            </div>
        </div>
        <div class="sm-container">
            <div style="padding-bottom: 10px">
                <a href="{{ url_for('front.apost') }}" class="btn btn-warning btn-block">发布帖子</a>
            </div>
            <div class="list-group">
                <a href="#" class="list-group-item active">所有板块</a>
                {% for board in boards %}
                    <a href="#" class="list-group-item">{{ board.name }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/front/front_signbase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>
</head>
<script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
<link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>
<script src="{{ static('common/zlparam.js') }}"></script>
<script src="{{ static(filename='common/sweetalert/xtalert.js') }}"></script>
<script src="{{ static(filename='common/sweetalert/sweetalert.min.js') }}"></script>
<link rel="stylesheet" href="{{ static(filename='common/sweetalert/sweetalert.css') }}">
<script src="{{ static(filename='common/zlajax.js') }}"></script>
<link rel="stylesheet" href="{{ static('front/css/front_signbase.css') }}">
{% block head %}
{% endblock %}
<body>
<div class="outer-box">
    <div class="logo-box">
        <a href="/">
            <img src="https://ss0.bdstatic.com/94oJfD_bAAcT8t7mm9GUKT-xh_/timg?image&quality=100&size=b4000_4000&sec=1577630949&di=5e55a96cfb2fd697f9c139ab6a7db42f&src=http://pic.58pic.com/58pic/15/26/28/00758PICJiU_1024.png"
                 alt="">
        </a>
    </div>
    <h2 class="page-title">
        {% block h2_block %}
        {% endblock %}
    </h2>
    <div class="sign-box">
        {% block signbox %}{% endblock %}
    </div>
    <span style="display: none;" id="return-to-span">{{ return_to }}</span>
</div>
</body>
</html>

templates/front/front_signin.html
{% extends 'front/front_signbase.html' %}>
{% from 'common/_macros.html' import static %}

{% block title %}
    登录
{% endblock %}

{% block h2_block %}
    登录
{% endblock %}

{% block head %}
    <script src="{{ static('front/js/front_signin.js') }}"></script>
{% endblock %}

{% block signbox %}
    <div class="form-group">
        <input type="text" class="form-control" name="telephone" placeholder="手机号码">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="密码">
    </div>
    <div class="checkbox">
        <label>
            <input type="checkbox" name="remember" value="1">记住我
        </label>
    </div>
    <div class="form-group">
        <button class="btn btn-warning btn-block" id="submit-btn">立即登录</button>
    </div>
    <div class="from-group">
        <a href="{{ url_for('front.signup') }}" class="signup-link">没有账号？立即注册</a>
        <a href="#" class="resetpwd-link">找回密码</a>
    </div>
{% endblock %}

templates/front/front_signup.html
{% extends 'front/front_signbase.html' %}
{% from 'common/_macros.html' import  static %}

{% block title %}
    注册
{% endblock %}

{% block head %}
    <script src="{{ static('front/js/front_signup.js') }}"></script>
{% endblock %}

{% block h2_block %}
    注册
{% endblock %}

{% block signbox %}
    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control" name="telephone" placeholder="手机号码">
            <span class="input-group-btn">
                    <button id="sms-captcha-btn" class="btn btn-default">发送验证码</button>
                </span>
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control" name="username" placeholder="用户名">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <input type="password" class="form-control" name="password" placeholder="密码">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <input type="password" class="form-control" name="password2" placeholder="确认密码">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control" name="graph_captcha" placeholder="图形验证码">
            <span class="input-group-addon captcha-addon">
                    <img id="captcha-img" class="captcha-img" src="{{ url_for('common.graph_captcha') }}" alt="">
                </span>
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-warning btn-block" id="submit-btn">立即注册</button>
    </div>
{% endblock %}