apps/cms/models.py
from exts import db
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash


class CMSPermission:
    # 255的二进制方式来表示  1111 1111
    ALL_PERMISSION = 0b11111111
    # 1. 访问者权限
    VISITOR = 0b00000001
    # 2. 管理帖子权限
    POSTER = 0b00000010
    # 3.管理评论权限
    COMMENTER = 0b00000100
    # 4. 管理板块的权限
    BOARDER = 0b00001000
    # 5. 管理前台用户的权限
    FRONTER = 0b00010000
    # 6. 管理后台用户的权限
    CMSUSER = 0b00100000
    # 7. 管理后台管理员的权限
    ADMINER = 0b01000000


cms_role_user = db.Table(
    'cms_role_user',
    db.Column('cms_role_id', db.Integer, db.ForeignKey('cms_role.id'), primary_key=True),
    db.Column('cms_user_id', db.Integer, db.ForeignKey('cms_user.id'), primary_key=True)
)


class CMSRole(db.Model):
    __tablename__ = "cms_role"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(50), nullable=False)
    desc = db.Column(db.String(200), nullable=True)
    create_time = db.Column(db.DateTime, default=datetime.now)
    permissions = db.Column(db.Integer, default=CMSPermission.VISITOR)

    users = db.relationship('CmsUser', secondary=cms_role_user, backref='roles')


class CmsUser(db.Model):
    __tablename__ = "cms_user"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50), nullable=False, unique=True)
    join_time = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, username, password, email):
        self.username = username
        #
        self.password = password
        self.email = email

    @property
    def password(self):
        return self._password

    # 可以直接设置属性
    @password.setter
    def password(self, raw_password):
        self._password = generate_password_hash(raw_password)

    def check_password(self, raw_password):
        result = check_password_hash(self.password, raw_password)
        return result

    @property
    def permissons(self):
        if not self.roles:
            return 0
        # 获取用户的所有权限
        all_permissions = 0
        for role in self.roles:
            permissions = role.permissions
            all_permissions |= permissions
        return all_permissions

    def has_permission(self, permission):
        # 判断用户是否具有某权限
        return permission & self.permissons == permission

    @property
    def is_developer(self):
        return self.has_permission(CMSPermission.ALL_PERMISSION)

apps/cms/forms.py
from wtforms import Form, StringField, IntegerField
from wtforms.validators import Email, InputRequired, Length, EqualTo, ValidationError
from apps.forms import BaseForm


class LoginForm(BaseForm):
    email = StringField(validators=[Email(message="请输入正确的邮箱格式"), InputRequired(message="请输入邮箱")])
    password = StringField(validators=[Length(6, 20, message="请输入正确格式的密码")])
    remember = IntegerField()


class ResetPwdForm(BaseForm):
    oldpwd = StringField(validators=[Length(6, 20, message='请输入正确格式的旧密码')])
    newpwd = StringField(validators=[Length(6, 20, message='请输入正确格式的新密码')])
    newpwd2 = StringField(validators=[EqualTo("newpwd")])


class ResetEmailForm(BaseForm):
    newemail = StringField(validators=[Email(message="请输入正确的邮箱格式"), InputRequired(message="请输入邮箱")])
    emailcaptcha = StringField(validators=[Length(6, 20, message='请输入正确格式的验证码')])


class AddBanner(BaseForm):
    name = StringField(validators=[InputRequired(message="请输入轮播图名称")])
    image_url = StringField(validators=[InputRequired(message="请输入轮播图图片连接")])
    link_url = StringField(validators=[InputRequired(message="请输入轮播图跳转连接")])
    priority = IntegerField(validators=[InputRequired(message="请输入轮播图优先级")])

    def validate_priority(self, field):
        priority_number = field.data
        if float(priority_number) > 100 or float(priority_number) < 0:
            raise ValidationError(message="权重在0-100之间")


class UpdateBannerForm(AddBanner):
    banner_id = IntegerField(validators=[InputRequired(message="请输入轮播图ID")])


class AddBoardForm(BaseForm):
    name = StringField(validators=[InputRequired(message="请输入版本名称")])


class UpdateBoardForm(AddBoardForm):
    board_id = IntegerField(validators=[InputRequired(message="请输入板块ID")])

apps/cms/__init__.py
from .views import bp
from .hooks import before_request

apps/cms/views.py
import random
import string
from flask_mail import Message
from flask.blueprints import Blueprint
from flask import views, g
from flask import render_template
from flask import request
from flask import session
from flask import redirect
from flask import url_for
from flask import g

from exts import db
from .forms import LoginForm
from .forms import ResetPwdForm
from .forms import ResetEmailForm
from .models import CmsUser
from ..models import BannerModel
from .decorators import login_required
from .decorators import permission_required
from config import CMS_USER_ID
from utils.restful import *
from exts import mail
from utils import cache
from .models import CMSPermission
from .forms import AddBanner
from .forms import UpdateBannerForm
from .forms import AddBoardForm
from .forms import UpdateBoardForm
from apps.models import BoardModel

bp = Blueprint("cms", __name__, url_prefix="/cms")


@bp.route('/')
@login_required
def index():
    # g.cms_user
    return render_template('cms/cms_index.html')


@bp.route('/logout/')
@login_required
def log_out():
    del session[CMS_USER_ID]
    return redirect(url_for('cms.login'))


@bp.route('/profile/')
@login_required
def profile():
    return render_template('cms/cms_profile.html')


@bp.route('/email/')
@login_required
def send_email():
    message = Message("验证码",recipients=['15201403874@163.com'],body="测试")
    try:
        mail.send(message)
    except Exception as e:
        server_error(msg=e)
    return "邮件发送成功"


@bp.route('/posts/')
@login_required
@permission_required(CMSPermission.POSTER)
def posts():
    return render_template('cms/cms_posts.html')


@bp.route('/comments/')
@login_required
@permission_required(CMSPermission.COMMENTER)
def comments():
    return render_template('cms/cms_comments.html')


@bp.route('/boards/')
@login_required
@permission_required(CMSPermission.BOARDER)
def boards():
    boards = BoardModel.query.filter_by().all()
    context = {
        'boards': boards
    }
    return render_template('cms/cms_boards.html', **context)


@bp.route('/aboard/', methods=["POST"])
@login_required
@permission_required(CMSPermission.BOARDER)
def aboard():
    form = AddBoardForm(request.form)
    if form.validate():
        name = form.name.data
        board = BoardModel(name=name)
        db.session.add(board)
        db.session.commit()
        return success()
    else:
        return params_error(msg=form.get_error())


@bp.route('/uboard/', methods=["POST"])
@login_required
@permission_required(CMSPermission.BOARDER)
def uboard():
    form = UpdateBoardForm(request.form)
    if form.validate():
        board_id = form.board_id.data
        name = form.name.data
        board = BoardModel.query.get(board_id)
        if board:
            board.name = name
            db.session.commit()
            return success()
        return params_error(msg="板块不存在")
    else:
        return params_error(form.get_error())


@bp.route('/dboard/', methods=["POST"])
@login_required
@permission_required(CMSPermission.BOARDER)
def dboard():
    board_id = request.form.get("board_id")
    if not board_id:
        return params_error(msg="请传入板块id")
    board = BoardModel.query.get(board_id)
    if not board:
        return params_error(msg="板块不存在")
    db.session.delete(board)
    db.session.commit()
    return success()


@bp.route('/fusers/')
@login_required
@permission_required(CMSPermission.FRONTER)
def fusers():
    return render_template('cms/cms_fusers.html')


@bp.route('/cusers/')
@login_required
@permission_required(CMSPermission.CMSUSER)
def cusers():
    return render_template('cms/cms_cusers.html')


@bp.route('/croles/')
@login_required
@permission_required(CMSPermission.ALL_PERMISSION)
def croles():
    return render_template('cms/cms_croles.html')


@bp.route('/banners/')
@login_required
def banners():
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).all()
    return render_template('cms/cms_banners.html', banners=banners)


@bp.route('/abanner/', methods=["POST"])
@login_required
def abanner():
    form = AddBanner(request.form)
    if form.validate():
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel(name=name, image_url=image_url, link_url=link_url, priority=priority)
        db.session.add(banner)
        db.session.commit()
        return success()
    else:
        return params_error(form.get_error())


@bp.route('/ubanner/', methods=["POST"])
def ubanner():
    form = UpdateBannerForm(request.form)
    if form.validate():
        banner_id = form.banner_id.data
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel.query.get(banner_id)
        if banner:
            banner.name = name
            banner.image_url = image_url
            banner.link_url = link_url
            banner.priority = priority
            db.session.commit()
            return success()
        else:
            return params_error(msg="轮播图不存在")
    else:
        return params_error(msg=form.get_error())


@bp.route('/dbanner/', methods=["POST"])
def dbanner():
    banner_id = request.form.get('banner_id')
    if not banner_id:
        return params_error("请输入bannerId")
    banner = BannerModel.query.get(banner_id)
    if not banner:
        return params_error("轮播图不存在")
    db.session.delete(banner)
    db.session.commit()
    return success()


@bp.route('/email_captcha/')
def email_captcha():
    email = request.args.get("email")
    if not email:
        return params_error('邮箱地址为空')
    # 生成验证码
    source = list(string.ascii_letters)
    source.extend([str(i) for i in range(0, 10)])
    captcha = "".join(random.sample(source, 6))

    # 发送
    message = Message(subject="验证码", recipients=[email], body="您的验证码是：%s" % captcha)
    try:
        mail.send(message)
    except Exception as e:
        server_error(msg=e)
    cache.set(email, captcha)
    return success()


class LoginView(views.MethodView):

    def __render(self, error_msg=None):
        return render_template("cms/cms_login.html", error_msg=error_msg)

    def get(self):
        return self.__render()

    def post(self):
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = CmsUser.query.filter_by(email=email).first()
            if user and user.check_password(password):
                session[CMS_USER_ID] = user.id
                if remember:
                    # 如果设置session.permanent=True,那么过期时间是31天
                    session.permanent = True
                return redirect(url_for('cms.index'))
            else:
                return params_error("邮箱或密码错误")

        else:
            msg = form.get_error()
            return params_error(msg)


class ResetPwdView(views.MethodView):
    decorators = [login_required]

    def __render(self, error_msg=None):
        return render_template("cms/cms_resetpwd.html", error_msg=error_msg)

    def get(self):
        return self.__render()

    def post(self):
        form = ResetPwdForm(request.form)
        if form.validate():
            oldpwd = form.oldpwd.data
            newpwd = form.newpwd.data
            user = g.cms_user
            if user.check_password(oldpwd):
                user.password = newpwd
                # db.session.add(user)
                db.session.commit()
                # {"code": 200, "msg": ""success}
                # return jsonify({"code": 200, "msg": "success"})
                return success()
            else:
                return params_error("旧密码错误！")
        else:
            msg = form.get_error()
            return params_error(msg=msg)


class ResetEmailView(views.MethodView):
    decorators = [login_required]

    def get(self):
        return render_template('cms/cms_resetemail.html')

    def post(self):
        form = ResetEmailForm(request.form)
        if form.validate():
            user = g.cms_user
            new_eamil = form.newemail.data
            email_captcha = form.emailcaptcha.data
            if email_captcha == cache.get(new_eamil):
                user.email = new_eamil
                db.session.commit()
                return success()
            else:
                return params_error(msg="验证码错误")
        else:
            msg = form.get_error()
            return params_error(msg=msg)


bp.add_url_rule('/login/', view_func=LoginView.as_view('login'))
bp.add_url_rule('/resetpwd/', view_func=ResetPwdView.as_view('resetpwd'))
bp.add_url_rule('/resetemail/', view_func=ResetEmailView.as_view('resetemail'))

templates/cms/cms_banners.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}
    轮播图管理
{% endblock %}

{% block head %}
    <script src="{{ static('cms/js/banner.js') }}"></script>
    <style>
        .top-box button {
            float: right;
        }
    </style>
{% endblock %}
{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}

    <div class="top-box">
        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#banner-dialog">
            添加轮播图
        </button>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>名称</th>
            <th>图片链接</th>
            <th>跳转链接</th>
            <th>优先级</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for banner in banners %}
            <tr data-name="{{ banner.name }}" data-image="{{ banner.image_url }}"
                data-link="{{ banner.link_url }}" data-priority="{{ banner.priority }}"
                data-id="{{ banner.id }}">
                <td>{{ banner.name }}</td>
                <td><a href="{{ banner.image_url }}" target="_blank">{{ banner.image_url }}</a></td>
                <td><a href="{{ banner.link_url }}" target="_blank">{{ banner.link_url }}</a> </td>
                <td>{{ banner.priority }}</td>
                <td>{{ banner.create_time }}</td>
                <td>
                    <button class="btn btn-default btn-xs edit-banner-btn">编辑</button>
                    <button class="btn btn-danger btn-xs delete-banner-btn">删除</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <!-- Modal -->
    <div class="modal fade" id="banner-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">添加轮播图</h4>
                </div>
                <div class="modal-body">
                    <form action="" class="form-horizontal">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">名称：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="name" placeholder="轮播图名称">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">图片：</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" name="image_url" placeholder="轮播图图片">
                            </div>
                            <button class="btn btn-info col-sm-2">添加图片</button>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">跳转：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="link_url" placeholder="跳转链接">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">权重：</label>
                            <div class="col-sm-10">
                                <input type="number" class="form-control" name="priority" placeholder="优先级">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button type="button" class="btn btn-primary" id="save-banner-btn">保存</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/cms/cms_base.html
{% from "common/_macros.html" import static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include 'common/_heads.html' %}
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href={{ static(filename='cms/css/base.css') }}>
    <script src="{{ static(filename='cms/js/base.js') }}"></script>
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">论坛CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url_for('cms.profile') }}">{{ g.cms_user.username }}<span></span></a></li>
                <li><a href={{ url_for('cms.log_out') }}>注销</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="查找...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                        <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                        <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                    </ul>
                </li>

                {% set user_data=g.cms_user %}
                <li class="nav-group banner-manage"><a href="{{ url_for('cms.banners') }}">轮播图管理</a></li>
                {% if user_data.has_permission(CMSPermission.POSTER) %}
                    <li class="nav-group post-manage"><a href="{{ url_for('cms.posts') }}">帖子管理</a></li>
                {% endif %}
                {% if user_data.has_permission(CMSPermission.COMMENTER) %}
                    <li class="comments-manage"><a href="{{ url_for('cms.comments') }}">评论管理</a></li>
                {% endif %}
                {% if user_data.has_permission(CMSPermission.BOARDER) %}
                    <li class="board-manage"><a href="{{ url_for('cms.boards') }}">板块管理</a></li>
                {% endif %}
                {% if user_data.has_permission(CMSPermission.FRONTER) %}
                    <li class="nav-group user-manage"><a href="{{ url_for('cms.fusers') }}">前台用户管理</a></li>
                {% endif %}
                {% if user_data.has_permission(CMSPermission.CMSUSER) %}
                    <li class="nav-group cmsuser-manage"><a href="{{ url_for('cms.cusers') }}">CMS用户管理</a></li>
                {% endif %}
                {% if user_data.is_developer %}
                    <li class="cmsrole-manage"><a href="{{ url_for('cms.croles') }}">CMS组管理</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %}{% endblock %}</h1>
            <div class="main_content">
                {% block main_content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/cms/cms_boards.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}


{% block title %}
    板块管理
{% endblock %}

{% block head %}
    <script src="{{ static('cms/js/boards.js') }}"></script>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <div class="top-box">
        <button class="btn btn-warning" style="float: right" id="add-board-btn">添加新板块</button>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>板块名称</th>
            <th>帖子数量</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for board in boards %}
            <tr data-name="{{ board.name }}" data-id="{{ board.id }}">
                <td>{{ board.name }}</td>
                <td>1</td>
                <td>{{ board.create_time }}</td>
                <td>
                    <button class="btn btn-default btn-xs edit-board-btn">编辑</button>
                    <button class="btn btn-danger btn-xs delete-board-btn">删除</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/cms/cms_comments.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    评论管理
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    这是评论管理页面
{% endblock %}

templates/cms/cms_croles.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    cms组管理
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    这是cms组管理页面
{% endblock %}

templates/cms/cms_cusers.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    cms用户管理
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    这是cms用户管理页面
{% endblock %}

templates/cms/cms_fusers.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    前台用户管理
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    这是前台用户管理页面
{% endblock %}

templates/cms/cms_index.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    BBS论坛管理系统
{% endblock %}

{% block page_title %}
    欢迎来到BBS论坛管理系统
{% endblock %}

templates/cms/cms_login.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>BBS论坛</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static',filename='cms/css/signin.css') }}" rel="stylesheet">

</head>

<body>

<div class="container">

    <form class="form-signin" method="post">
        <h2 class="form-signin-heading">请登录</h2>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <label for="inputEmail" class="sr-only">邮箱：</label>
        <input name="email" type="email" id="inputEmail" class="form-control" placeholder="邮箱" required autofocus>
        <label for="inputPassword" class="sr-only">密码： </label>
        <input name="password" type="password" id="inputPassword" class="form-control" placeholder="密码" required>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="1" name="remember"> 记住我
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">立即登录</button>
    </form>
    {% if error_msg %}
        <p style="text-align: center" class="text-danger">
            {{ error_msg }}
        </p>
    {% endif %}
</div> <!-- /container -->
</body>
</html>

templates/cms/cms_posts.html
{% extends 'cms/cms_base.html' %}

{% block title %}
   帖子管理
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    这是帖子管理页面
{% endblock %}

templates/cms/cms_profile.html
{% extends 'cms/cms_base.html' %}
{% from "common/_macros.html" import set_table %}

{% block title %}
    个人信息
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <table class="table table-bordered">
        {% set user_data=g.cms_user %}
        <tr>
            <td>用户名：</td>
            <td>{{ user_data.username }}</td>
        </tr>
        <tr>
            <td>邮箱：</td>
            <td>{{ user_data.email }}</td>
        </tr>
        <tr>
            <td>角色：</td>
            <td>
                {% for role in user_data.roles %}
                    {{ role.name }}
                    {% if not loop.last %},{% endif %}
                {% endfor %}
            </td>
        </tr>
        <tr>
            <td>权限：</td>
            <td>
                {% for role  in user_data.roles %}
                    {{ role.desc }}
                    {% if not loop.last %}/{% endif %}
                {% endfor %}
                
                
            </td>
        </tr>
        <tr>
            <td>加入时间：</td>
            <td>{{ user_data.join_time }}</td>
        </tr>
    </table>
{% endblock %}

templates/cms/cms_resetemail.html
{% extends 'cms/cms_base.html' %}

{% block title -%}
    修改邮箱
{%- endblock %}

{% block head %}
    <script src="{{ static("cms/js/resetemail.js") }}"></script>
{% endblock %}

{% block page_title -%}
    {{ self.title() }}
{%- endblock %}


{% block main_content %}
    <form action="" method="post">
        <div class="form-container">
            <div class="form-group">
                <div class="input-group">
                    <input type="email" class="form-control" name="email" placeholder="邮箱">
                    <span class="input-group-addon" id="captcha-btn" style="cursor:pointer;">获取验证码</span>
                </div>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="captcha" placeholder="邮箱验证码">
            </div>
            <div class="form-group">
                <button type="submit" id="submit" class="btn btn-primary">立即修改</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/cms/cms_resetpwd.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import resetpwd %}
{% from 'common/_macros.html' import static %}
{% from 'common/_macros.html' import render_err_msg %}

{% block title -%}
    修改密码
{%- endblock %}

{% block page_title -%}
    {{ self.title() }}
{%- endblock %}

{% block head %}
    <script src="{{ static("cms/js/resetpwd.js") }}"></script>
{% endblock %}


{% block main_content %}
    <form action="" method="post">
        <div class="form-container">
            {{ resetpwd("旧密码","oldpwd","请输入原始密码") }}
            {{ resetpwd("新密码","newpwd","输入新密码") }}
            {{ resetpwd("确认密码","newpwd2","确认新密码") }}
            <button type="submit" id="submit" class="btn btn-primary">立即修改</button>
        </div>
    </form>
{% endblock %}

templates/cms/test.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Simple table</title>
    <link href="minimal-table.css" rel="stylesheet" type="text/css">
  </head>
  <body>
    <h1>Simple table</h1>

    <table class="table table-bordered">
      <tr>
        <td>Hi, I'm your first cell.</td>
        <td>I'm your second cell.</td>
        <td>I'm your third cell.</td>
        <td>I'm your fourth cell.</td>
      </tr>
      <tr>
        <td>Second row, first cell.</td>
        <td>Cell 2.</td>
        <td>Cell 3.</td>
        <td>Cell 4.</td>
      </tr>
    </table>
  </body>
</html>